### ISSUE TITLE
SyntaxError: Use of const in strict mode. with lint-staged

### ISSUE THREAD

**Issue by jitendravyas** [typicode/husky#129]
❯ git commit -m "feat(grunt): testtttttt" 

> husky - npm run -s precommit

/Users/jitendravyas/app-v3/node_modules/lint-staged/src/index.js:6
const path = require('path')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jitendravyas/app-v3/node_modules/lint-staged/index.js:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

> husky - pre-commit hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit'

**Comment by onbjerg** [comment]
Seems like an issue in [okonet/lint-staged](https://github.com/okonet/lint-staged), not Husky.

**Comment by ggTravelodge** [comment]
@onbjerg  not sure if that is true as I also get it for eslint
npm: '4.2.0'
node: '7.10.0'
> husky - npm run -s prepush
/Users/gajjargaurav/test/service/node_modules/eslint/bin/eslint.js:16
const useStdIn = (process.argv.indexOf("--stdin") > -1),
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by gajjargaurav** [comment]
@onbjerg  not sure if that is true as I also get it for eslint
npm: '4.2.0'
node: '7.10.0'
> husky - npm run -s prepush
/Users/gajjargaurav/service/node_modules/eslint/bin/eslint.js:16
const useStdIn = (process.argv.indexOf("--stdin") > -1),
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by mmoutenot** [comment]
@gajjargaurav I ran into this, and it seems like Husky was picking the "wrong" node version. To fix, and force it to use the correct version via `nvm` I added an `.nvmrc` file with the version number I needed.

Hope this helps.

**Comment by gajjargaurav** [comment]
@mmoutenot that is interesting as I don't use nvm I use https://github.com/tj/n

**Comment by gajjargaurav** [comment]
@mmoutenot following your lead I investigated it further and found a solution!

I've added my answer on a [stackoverflow question](https://stackoverflow.com/questions/43932038/husky-giving-error-syntaxerror-use-of-const-in-strict-mode/44168690#44168690) I believe posted by the same user who raised this issue.

**Comment by mmoutenot** [comment]
hooray!

**Comment by typicode** [comment]
Thank you for the updates on this issue and sorry for the confusion.
To make it more obvious which version of Node is used, I've added `node -v` to husky output.

**Comment by pencilcheck** [comment]
Set the default nvm version so husky will use the correct one
https://eric.blog/2016/08/23/set-default-node-version-with-nvm/
