### ISSUE TITLE
GUI Git Hook fails when env defined in .npmrc

### ISSUE THREAD

**Issue by chrisblossom** [typicode/husky#131]
my .npmrc:
```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
save-exact = true
```

```
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F /var/folders/hm/n_tq5p6j7j313n28pjzvk63c0000gn/T/SourceTreeTemp.SaYrXv -a 
Error: Failed to replace env in config: ${NPM_TOKEN}
    at /Users/chris/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/core.js:418:13
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at envReplace (/Users/chris/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/core.js:414:12)
    at parseField (/Users/chris/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/core.js:392:7)
    at /Users/chris/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/core.js:335:17
    at Array.forEach (native)
    at Conf.add (/Users/chris/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/core.js:334:23)
    at ConfigChain.addString (/Users/chris/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v6.10.3 --silent` to unset it.
Found '/Users/chris/github/app/.nvmrc' with version <6.10.3>
Error: Failed to replace env in config: ${NPM_TOKEN}
    at /Users/chris/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/core.js:418:13
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at envReplace (/Users/chris/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/core.js:414:12)
    at parseField (/Users/chris/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/core.js:392:7)
    at /Users/chris/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/core.js:335:17
    at Array.forEach (native)
    at Conf.add (/Users/chris/.nvm/versions/node/v6.10.3/lib/node_modules/npm/lib/config/core.js:334:23)
    at ConfigChain.addString (/Users/chris/.nvm/versions/node/v6.10.3/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v6.10.3` to unset it.
> husky - Can't find npm in PATH. Skipping precommit script in package.json
Completed successfully
```

**Comment by MikelArnaiz** [comment]
Same here.

In Sourcetree and Fork the precommit is not run allowing you to commit.

In my `.npmrc` I have:

    //rll.jfrog.io/rll/api/npm/my-npm/:_authToken=${NPM_TOKEN}
    engine-strict=true

Modifying `./.git/hooks/pre-commit` after the message `husky > can't find npm in PATH, skipping precommit script in package.json` with an `exit 1` instead `exit 0` will abort the commit and give you the error message:

```
Pre-commit hook 'pre-commit' has failed:

Error: Failed to replace env in config: ${NPM_TOKEN}
    at /Users/MY-USERNAME/.nvm/versions/node/v10.4.1/lib/node_modules/npm/lib/config/core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (/Users/MY-USERNAME/.nvm/versions/node/v10.4.1/lib/node_modules/npm/lib/config/core.js:411:12)
    at parseField (/Users/MY-USERNAME/.nvm/versions/node/v10.4.1/lib/node_modules/npm/lib/config/core.js:389:7)
    at /Users/MY-USERNAME/.nvm/versions/node/v10.4.1/lib/node_modules/npm/lib/config/core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (/Users/MY-USERNAME/.nvm/versions/node/v10.4.1/lib/node_modules/npm/lib/config/core.js:328:23)
    at ConfigChain.addString (/Users/MY-USERNAME/.nvm/versions/node/v10.4.1/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (/Users/MY-USERNAME/.nvm/versions/node/v10.4.1/lib/node_modules/npm/lib/config/core.js:316:10)
    at /Users/MY-USERNAME/.nvm/versions/node/v10.4.1/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
/Users/MY-USERNAME/.nvm/versions/node/v10.4.1/lib/node_modules/npm/lib/npm.js:61
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/Users/MY-USERNAME/.nvm/versions/node/v10.4.1/lib/node_modules/npm/lib/npm.js:61:13)
    at process.errorHandler (/Users/MY-USERNAME/.nvm/versions/node/v10.4.1/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:448:27)
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v10.4.1 --silent` to unset it.
husky > can't find npm in PATH, skipping precommit script in package.json
```

I see that indeed that npm is not in the `PATH`, which is:

    echo $PATH
    /Users/MY-USERNAME/.nvm/versions/node/v10.4.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

but `husky` sees this `PATH`

    /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local

As you can see I'm using `nvm`

**Comment by manuel-reil** [comment]
Have you guys found a solution to this?

**Comment by lukeselbeck** [comment]
I'm still getting this, why was this closed?  What's the solution?

**Comment by lukeselbeck** [comment]
Figured out my problem.  For any future peoples:  I was commiting/pushing with vscode and that was giving me the above error.  When I commit/push with the terminal, it works fine!

**Comment by Ethaan** [comment]
@lukeselbeck i'm commiting/pushing using git kraken and visual studio, there should be a way to export variables for hooks

**Comment by antikvarBE** [comment]
Yes, why is this closed?

**Comment by sexta13** [comment]
I'm facing same issue as well...

**Comment by paschalidi** [comment]
still having this issue when I am committing with gitkraken. Perhaps we could reopen @chrisblossom

**Comment by chrisblossom** [comment]
> Still having this issue when I am committing with gitkraken. Perhaps we could reopen, @chrisblossom what you think?

Because this issue was created so long ago and I closed it without commenting why (my mistake, sorry!), I would recommend opening a new issue with a link to this issue in-case it is still relevant.

**Comment by paschalidi** [comment]
Will do thanks

**Comment by SalahAdDin** [comment]
I'm facing this problem again, with the last `husky` version.

**Comment by MacRayy** [comment]
I'm having the same issue with GitKraken

**Comment by carpben** [comment]
Facing the same issue with Sourcetree.

**Comment by YousefMMS** [comment]
Having the same issue with Sourcetree & vscode

**Comment by carpben** [comment]
I published a solution on StackOverflow. Can you please try it out and let me know if it works for you too? 
https://stackoverflow.com/questions/135688/setting-environment-variables-on-os-x/70959181#70959181

**Comment by michealroberts** [comment]
This should't be closed as the above fix does not work for me, using Github Desktop.
