### ISSUE TITLE
Husky init fails using Bun

### ISSUE THREAD

**Issue by aabanaag** [typicode/husky#1452]
**Troubleshoot**
- [x] Before creating an issue, please check:
https://typicode.github.io/husky/troubleshoot.html

If you're migrating from husky 4, see:
https://typicode.github.io/husky/migrate-from-v4.html

**Context**
Please describe your issue and provide some context:
- Terminal or GUI client (PowerShell, Git Bash, GitHub Desktop, ...)
- If applicable, content of the failing hook
- If possible, minimal steps to reproduce the issue

Running Bun, I'm upgrading from v4 to latest (v9)
After installing husky via (`bun add --dev husky`), running `bunx husky init` fails and returns a SyntaxError

```
$ bunx husky init
file:///Users/jongbanaag/node_modules/husky/bin.mjs:14
        ;(o.scripts ||= {}).prepare = 'husky'
                      ^

SyntaxError: Unexpected token '='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

Thank you!

**Comment by aabanaag** [comment]
Closing this, my default node version is 12 which caused the error. Using node >12 fixed the issue for me
