### ISSUE TITLE
 npm ERR! husky@0.14.3 install: `node ./bin/install.js`

### ISSUE THREAD

**Issue by Nomadu** [typicode/husky#196]
Trying to build Wire-desktop. Saw elsewhere in comments that it might have something to do with version of node or the path. Am noob, unsure how to proceed.

npm ERR! Linux 4.8.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! husky@0.14.3 install: `node ./bin/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the husky@0.14.3 install script 'node ./bin/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the husky package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js

**Comment by duckworth** [comment]
Same issue trying to install on Ubuntu 16.04 with node v6.11.4 and npm 5.5.1. 
```

30720 silly install husky@0.14.3
30721 info lifecycle husky@0.14.3~install: husky@0.14.3
30722 verbose lifecycle husky@0.14.3~install: unsafe-perm in lifecycle false
30723 verbose lifecycle husky@0.14.3~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/repos/FrontEndRelease/node_modules/husky/node_modules/.bin:/root/repos/FrontEndRelease/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/snap/bin
30724 verbose lifecycle husky@0.14.3~install: CWD: /root/repos/FrontEndRelease/node_modules/husky
30725 silly lifecycle husky@0.14.3~install: Args: [ '-c', 'node ./bin/install.js' ]
30726 silly lifecycle husky@0.14.3~install: Returned: code: 1  signal: null
30727 info lifecycle husky@0.14.3~install: Failed to exec install script
30728 verbose unlock done using /root/.npm/_locks/staging-24b62a714eddd517.lock for /root/repos/FrontEndRelease/node_modules/.staging
30729 verbose stack Error: husky@0.14.3 install: `node ./bin/install.js`
30729 verbose stack Exit status 1
30729 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
30729 verbose stack     at emitTwo (events.js:106:13)
30729 verbose stack     at EventEmitter.emit (events.js:191:7)
30729 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
30729 verbose stack     at emitTwo (events.js:106:13)
30729 verbose stack     at ChildProcess.emit (events.js:191:7)
30729 verbose stack     at maybeClose (internal/child_process.js:920:16)
30729 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
30730 verbose pkgid husky@0.14.3
30731 verbose cwd /root/repos/FrontEndRelease
30732 verbose Linux 4.4.0-1022-aws
30733 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
30734 verbose node v6.11.4
30735 verbose npm  v5.5.1
30736 error code ELIFECYCLE
30737 error errno 1
30738 error husky@0.14.3 install: `node ./bin/install.js`
30738 error Exit status 1
30739 error Failed at the husky@0.14.3 install script.
30739 error This is probably not a problem with npm. There is likely additional logging output above.
30740 verbose exit [ 1, true ]


```

**Comment by BingBlog** [comment]
Same issue trying to install on Ubuntu with node v4.2.6 and npm 3.5.2.

**Comment by pjclutterbuck** [comment]
Same issue trying to install on Mint 18.3 (xenial based) with node 9.3.0 and npm  5.5.1

**Comment by adamyi** [comment]
same here with node 6.13.1 and npm 3.10.10 on debian

**Comment by kindy** [comment]
can you try to run **npm install** with `--unsafe-perm` options?
maybe it can resolve this problem.

**Comment by leeypp** [comment]
same here with node 9.9.0 and npm 6.5.0 on centos 7.2
```
865 error file sh
866 error code ELIFECYCLE
867 error errno ENOENT
868 error syscall spawn
869 error husky@0.14.3 install: `node ./bin/install.js`
869 error spawn ENOENT
870 error Failed at the husky@0.14.3 install script.
870 error This is probably not a problem with npm. There is likely additional logging output above.
871 verbose exit [ 1, true ]
```

**Comment by goforu** [comment]
Any workaround? I'm using node v10.15.3 npm 6.9.0

Cannot find module 'node_modules/husky/bin/install.js

**Comment by When-Jay** [comment]
I got same problem,

**Comment by When-Jay** [comment]
`npm install husky@0.13.4 --unsafe-perm` 
and `npm audit fix`
maybe help!

**Comment by typicode** [comment]
Closing as the issue shouldn't appear in v5. Thanks for the report and the solution shared at the end :+1:

**Comment by youndyan** [comment]
You can try deleting this in the config.json file
