### ISSUE TITLE
npm test script is run instead of my custom defined "precommit" script

### ISSUE THREAD

**Issue by denisflorkin** [typicode/husky#198]
Despite having `"precommit": "./hooks/precommit.sh"` in my package.json script section, it looks like when attempting to commit, the `npm test` script is run by husky instead.

Any idea why that could be happening ?

**Comment by rochapablo** [comment]
+1

**Comment by typicode** [comment]
Hi @denisflorkin,

Not sure why it's happening, there's no reference to `npm test` in `husky` code actually.
What's the content of `precommit.sh`?

You may want to check the content of `.git/hooks/pre-commit`.

**Comment by denisflorkin** [comment]
Hello,
sorry for the delai,

`.git/hooks/pre-commit` is as follows :
```
#!/bin/bash
./node_modules/pre-commit/hook
RESULT=$?
[ $RESULT -ne 0 ] && exit 1
exit 0

```

and the `hooks/precommit.sh`
```
#!/bin/bash


set -e

G_BRANCH=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

echo 'precommit hook running...'
echo "on branch $G_BRANCH"

# we only care to keep dev clean
if [ $G_BRANCH == 'develop' ]; then
  npm run lint &&\
  npm run test:coverage &&\
  npm run jestCoverageRatchet
else
  exit 0
fi
```

When I try to commit it’s not invoking the precommit.sh, it looks like the npm test command is ran instead.

**Comment by rochapablo** [comment]
When I run ```npm run tests``` there's no error

```
$ npm run test

> @0.1.0 test /my-app
> node node_modules/jest/bin/jest.js

 PASS  src/components/loading/index.test.tsx
 PASS  src/containers/login/index.test.tsx

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        5.083s
Ran all test suites.
```

But running ```git commit```

```
Pablos-MBP:buroy pablo$ git commit -m "test"
husky > npm run -s precommit (node v6.11.3)

 PASS  src/components/loading/index.test.tsx
 FAIL  src/containers/login/index.test.tsx
  ● Test suite failed to run

    /my-app/src/config/navigator.tsx:13
        ...settings,
        ^^^

    SyntaxError: Unexpected token ...

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (src/store/reducers/index.ts:2:18)
      at Object.<anonymous> (src/store/index.ts:6:17)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        4.867s, estimated 5s
Ran all test suites.
```

Also that's not my node version, the real one is

```
$ node -v
v8.9.1
```

**Comment by carera** [comment]
@denisflorkin The fact that you have `./node_modules/pre-commit/hook` in your pre-commit file only means that you are also trying `pre-commit npm library which is most likely conflicting
