### ISSUE TITLE
husky 1.0.0-rc.1: change to HUSKY_GIT_PARAMS break commitlint

### ISSUE THREAD

**Issue by sandangel** [typicode/husky#268]
commitlint work well with 0.15.0-rc.13, but when upgrade to 1.0.0-rc.1, I have this error

```sh
25h25hhusky > commit-msg (node v8.11.1)
Debugger listening on ws://127.0.0.1:9229/8ff01629-2274-4052-b37b-51090eb51667
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
D:\Web\Browser\NgRx\ngrx-utils\node_modules\@commitlint\cli\lib\cli.js:70
                throw err;
                ^

Error: Received $GIT_PARAMS as value for -e | --edit, but GIT_PARAMS is not available globally.
    at normalizeEdit (D:\Web\Browser\NgRx\ngrx-utils\node_modules\@commitlint\cli\lib\cli.js:183:10)
    at normalizeFlags (D:\Web\Browser\NgRx\ngrx-utils\node_modules\@commitlint\cli\lib\cli.js:169:40)
    at D:\Web\Browser\NgRx\ngrx-utils\node_modules\@commitlint\cli\lib\cli.js:79:11
    at new Promise (<anonymous>)
```

**Comment by typicode** [comment]
Thanks for the report, could you try with:

```
"husky": {
  "hooks": {
    "commit-msg": "commitlint -e $HUSKY_GIT_PARAMS"
  }
}
```

2018-04-11 3:15 GMT+02:00 San Nguyen <notifications@github.com>:

**Comment by sandangel** [comment]
Hi, I have tried with -e $HUSKY_GIT_PARAMS, It worked as expected. I think you should document this in the README.

**Comment by typicode** [comment]
My bad, thought I did but apparently only in CHANGELOG.md, will update docs.md as well. Thanks.

**Comment by sandangel** [comment]
Hi, I have test this on windows machine and it not worked.
Switch back to 0.15.0-rc.13 work fine.

```sh
25h25hhusky > commit-msg (node v8.11.1)
D:\Web\Browser\NgRx\ngrx-utils\node_modules\@commitlint\cli\lib\cli.js:70
                throw err;
                ^

Error: ENOENT: no such file or directory, open 'D:\Web\Browser\NgRx\ngrx-utils\$HUSKY_GIT_PARAMS'
husky > commit-msg hook failed (add --no-verify to bypass)
D:\Web\Browser\NgRx\ngrx-utils\node_modules\commitizen\dist\cli\strategies\git-cz.js:102
        throw error;
        ^

Error: git exited with error code 1
    at ChildProcess.<anonymous> (D:\Web\Browser\NgRx\ngrx-utils\node_modules\commitizen\dist\git\commit.js:50:26)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\Windows\\system32\\cmd.exe
```

**Comment by FabienDehopre** [comment]
I have the same issue on Windows. Same solution than @sandangel 

```
husky > commit-msg (node v8.11.1)
D:\dvlp\libs\opw-kernel\node_modules\@commitlint\cli\lib\cli.js:70
                throw err;
                ^

Error: ENOENT: no such file or directory, open 'D:\dvlp\libs\opw-kernel\$HUSKY_GIT_PARAMS'
husky > commit-msg hook failed (add --no-verify to bypass)
```

**Comment by FabienDehopre** [comment]
I still have this issue with the latest @next version which at this time is 1.0.0-rc.8

**Comment by typicode** [comment]
Thanks to @marionebl recent update, it should work better with commitlint `v7.0.0`.

@FabienDehopre could you try with the following script?

```json
"husky": {
  "hooks": {
    "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
  }
}
```

**Comment by FabienDehopre** [comment]
@typicode indeed, with the configuration you gave me, it works correctly.
It seems that the new way of passing the environment variable is not yet documented in the README file.

**Comment by indraraj26** [comment]
Hi, 
I am getting same error even though i am using 7+ version.
```
 "@commitlint/cli": "^7.5.2",
  "@commitlint/config-conventional": "^7.5.0",
```

` "husky": "^1.3.1",`

commitlint.config.js
`module.exports = {extends: ['@commitlint/config-conventional']}`

```
git commit -m "feat: initial commit"
husky > pre-commit (node v8.14.0)


All files pass linting.


All files pass linting.
husky > commit-msg (node v8.14.0)
D:\ng\commitlint.config.js:1
(function (exports, require, module, __filename, __dirname) { ��m
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at requireFromString (D:\ng-sma\node_modules\require-from-string\index.js:28:4)
    at parseJsFile (D:\ng-sma\node_modules\cosmiconfig\dist\loadJs.js:15:15)
    at <anonymous>
husky > commit-msg hook failed (add --no-verify to bypass)
```
