### ISSUE TITLE
Exception when commiting from intellij webstorm

### ISSUE THREAD

**Issue by nosovsh** [typicode/husky#307]
Using "next" version of husky. Using pre-commit and pre-push hooks. Everything works from command line. But when commiting through intellij webstorm dialog getting the following error:

```
Commit failed with error
0 files committed, 1 file failed to commit: KD-16969	 pre-commit hook
*****/node_modules/husky/lib/runner/index.js:19
function default_1([, scriptPath, hookName = '', HUSKY_GIT_PARAMS], getStdinFn = getStdin // Used for mocking
         ^

SyntaxError: Unexpected token [
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:387:25)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/home/trashgenerator/workspace/kairion/frontend/node_modules/husky/lib/runner/bin.js:3:12)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
```

Seems like webstorm is using old node? Any ideas how to fix it? in IDE settings I have node v9

**Comment by typicode** [comment]
Hi @nosovsh 

I don't have WebStorm installed but can you check if you have a `~/.node_path` file? Is there an old node version referenced in it? I'd try removing `~/.node_path` and giving another try with WebStorm.

**Comment by golanBar** [comment]
Hi @typicode ,

I have the same problem. It happens both in smartgit and in pycharm, and I don't have a .node_path file in my home directory.
Can you please advise?

Thanks
