### ISSUE TITLE
Husky Failing on Commit

### ISSUE THREAD

**Issue by chriscrosscutler** [typicode/husky#317]
I'm running husky on my Mac and keep getting this error when trying to commit:

```
Husky > unexpected error { JSONError: Unexpected token } in JSON at position 666 while parsing near '...-recursive",      },  "engines": {  ...'
    at module.exports.err (/Users/user/Desktop/Guardian/review-widget/node_modules/husky/node_modules/parse-json/index.js:26:19)
    at Function.module.exports.sync.options [as sync] (/Users/user/Desktop/Guardian/review-widget/node_modules/husky/node_modules/read-pkg/index.js:35:15)
    at Object.<anonymous> (/Users/user/Desktop/Guardian/review-widget/node_modules/husky/lib/runner/index.js:23:29)
    at next (native)
    at /Users/user/Desktop/Guardian/review-widget/node_modules/husky/lib/runner/index.js:7:71
    at __awaiter (/Users/user/Desktop/Guardian/review-widget/node_modules/husky/lib/runner/index.js:3:12)
    at Object.run [as default] (/Users/user/Desktop/Guardian/review-widget/node_modules/husky/lib/runner/index.js:21:12)
    at Object.<anonymous> (/Users/user/Desktop/Guardian/review-widget/node_modules/husky/lib/runner/bin.js:4:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10) name: 'JSONError' }
```

my package.json looks like this:
```json
  "lint-staged": {
    "*.js": [
      "./node_modules/.bin/eslint --fix",
      "git add"
    ]
  },
  "husky": {
    "hooks": {
      "precommit": "lint-staged && npm test"
    }
  }
```

Is this a Husky error or eslint error?

**Comment by typicode** [comment]
Hi @chriscrosscutler,

Based on on the error message, it seems to fail parsing your `package.json` somewhere nears '...-recursive". Maybe there's a typo in it, like an extra `,`.

**Comment by Deehoos** [comment]
Hi, we got the same error and it was a syntax error in our package.json file as typicode suggested. It was caused by a merge conflict
