### ISSUE TITLE
Commitlint Integration Issues with Husky@next

### ISSUE THREAD

**Issue by Undistraction** [typicode/husky#340]
I'm opening this here as it appears to be a problem with $HUSKY_GIT_PARAMS. If you think this is a problem with commitlint I'll close and move there.

I have the following in my `husky.config.js`:

```javascript
module.exports = {
  hooks: {
    'pre-commit': `npm test`,
    'commit-msg': `commitlint -E $HUSKY_PARAMS`,
  },
}
```

Tests run and I can enter a message, however there is an error on `commit-msg`:

```
husky > commit-msg (node v8.11.3)
/Users/me/Sites/app/node_modules/@commitlint/cli/lib/cli.js:103
        throw err;
        ^
Error: Recieved '.git/COMMIT_EDITMSG' as value for -E | --env, but environment variable '.git/COMMIT_EDITMSG' is not available globally
    at getEditValue (/Users/me/Sites/app/node_modules/@commitlint/cli/lib/cli.js:204:10)
    at normalizeFlags (/Users/me/Sites/app/node_modules/@commitlint/cli/lib/cli.js:197:15)
    at /Users/me/Sites/app/node_modules/@commitlint/cli/lib/cli.js:110:11
    at new Promise (<anonymous>)
    at main (/Users/me/Sites/app/node_modules/@commitlint/cli/lib/cli.js:107:9)
    at Object.<anonymous> (/Users/me/Sites/app/node_modules/@commitlint/cli/lib/cli.js:99:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
husky > commit-msg hook failed (add --no-verify to bypass)
```
The errror is raised by @commitlint/cli in this function:
```javascript
function getEditValue(flags) {
  if (flags.env) {
    if (!(flags.env in process.env)) {
      throw new Error(
        `Recieved '${
          flags.env
        }' as value for -E | --env, but environment variable '${
          flags.env
        }' is not available globally`
      )
    }
    return process.env[flags.env]
  }
```
Looking at `process.env` within that function, there is no `$HUSKY_GIT_PARAMS` available.

- node v8.11.3
- "husky": "^1.0.0-rc.13",
- "@commitlint/cli": "^7.1.2",
- "@commitlint/config-conventional": "^7.1.2",

**Comment by ripeBoy** [comment]
Hi,Why is it closed?How to solve?

**Comment by farzer** [comment]
problem here

**Comment by zhixinpeng** [comment]
'commit-msg': `commitlint -E $HUSKY_PARAMS`

the correct way to write it is:

'commit-msg': `commitlint -E HUSKY_PARAMS`

delete "$"
