### ISSUE TITLE
pre-commit hook failed ('Unable to detect a source control manager')

### ISSUE THREAD

**Issue by MAOstrander** [typicode/husky#383]
I was using this just fine on my Mac, but for reasons I switched to my Windows PC and now I get an error every time I try to do a git commit.

```
husky > pre-commit (node v10.11.0)
C:\projects\myProject\node_modules\pretty-quick\dist\index.js:38
    throw new Error('Unable to detect a source control manager.');

Error: Unable to detect a source control manager.
    at exports.default (C:\projects\myProject\node_modules\pretty-quick\dist\index.js:38:11)
    at Object.<anonymous> (C:\projects\myProject\node_modules\pretty-quick\bin\pretty-quick.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
husky > pre-commit hook failed (add --no-verify to bypass)
```

If I add `--no-verify` it commits and I can push no problem, but I'm not sure why it either can't detect the source control manager or what else is going wrong.
I'm using Cmder as my CLI if that matters.

**Comment by bartvanandel** [comment]
I'm also using Cmder on Windows but I haven't seen this happening here (FYI I'm not a Husky dev)

**Comment by typicode** [comment]
Seems to be an error thrown by pretty-quick:

```
Error: Unable to detect a source control manager.
    at exports.default (C:\projects\myProject\node_modules\pretty-quick\dist\index.js:38:11)
```

I don't know this project well enough to help here, sorry.

**Comment by ViceIce** [comment]
I'm having the same problem since git 2.24.0.windows.2 and node v12.13.0.

```
> pretty-quick --staged

C:\Users\kriese\projects\vsaf\vsaf-maintanance\node_modules\pretty-quick\dist\index.js:40
    throw new Error('Unable to detect a source control manager.');
```

**Comment by ViceIce** [comment]
https://github.com/azz/pretty-quick/issues/93
