### ISSUE TITLE
Husky install fail

### ISSUE THREAD

**Issue by Berkmann18** [typicode/husky#419]
Recently I've experienced an error that affects NodeJS >= 8 (maybe also v7 but not v6) and only on TravisCI (not on my local machine).
The error is the following:
```bash
> node husky install
internal/modules/cjs/loader.js:605
    throw err;
    ^
Error: Cannot find module 'parse-json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/travis/build/Berkmann18/TemplateJS/node_modules/cosmiconfig/dist/loaders.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

It started happening after moving some packages to `devDependencies` after experiencing some issues with `semantic-release` (which normally shouldn't affect `husky`).

[Reference log](https://travis-ci.org/Berkmann18/TemplateJS/jobs/464974366).

**Comment by oranze** [comment]
Same problem! Can't install any version!!!

**Comment by typicode** [comment]
Don't know what may have caused the issue :/
Closing as it may be fixed by newer versions.
