### ISSUE TITLE
The 'prepush' script of a dependency is preventing me from pushing my package

### ISSUE THREAD

**Issue by donmccurdy** [typicode/husky#501]
My project (https://github.com/donmccurdy/aframe-physics-system) depends on the `aframe` package (https://github.com/aframevr/aframe) as a peer and dev dependency. When trying to do `git push` on my package, I see the following error from husky:

```
$ git push

> aframe@0.9.2 prepush /Users/donmccurdy/Documents/Projects/aframe-physics-system/node_modules/aframe
> node scripts/testOnlyCheck.js

module.js:487
    throw err;
    ^

Error: Cannot find module '/Users/donmccurdy/Documents/Projects/aframe-physics-system/node_modules/aframe/scripts/testOnlyCheck.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aframe@0.9.2 prepush: `node scripts/testOnlyCheck.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aframe@0.9.2 prepush script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/donmccurdy/.npm/_logs/2019-06-11T04_33_32_088Z-debug.log

husky - pre-push hook failed (add --no-verify to bypass)

error: failed to push some refs to 'git@github.com:donmccurdy/aframe-physics-system.git'
```

I'm not (intentionally) using husky for this project, so I'm not sure why `prepush` scripts in my dependencies are being triggered. 😕

**Comment by donmccurdy** [comment]
`npm ls husky` comes up empty:

```
$ npm ls husky
aframe-physics-system@3.3.0 /Users/donmccurdy/Documents/Projects/aframe-physics-system
└── (empty)
```

**Comment by typicode** [comment]
Cleaning old issues. Sorry for the lack of reply, I hope you've found a workaround.
That said, this is not something that should happen if husky is used as a devDependency.
