### ISSUE TITLE
post-receive appeared to fire client side in WSL

### ISSUE THREAD

**Issue by devinrhode2** [typicode/husky#603]
My co-worker ran a simple git pull for our project inside a WSL terminal. After the git pull was done we had this error from husky:

```
internal/modules/cjs/loader.js:775
    throw err;
    Error: Cannot find module 'nice-try'
 - /mnt/d/work/dev/projects/mhp-new/node_modules/husky/node_modules/cross-spawn/lib/parse.js
 - /mnt/d/work/dev/projects/mhp-new/node_modules/husky/node_modules/cross-spawn/index.js    
 - /mnt/d/work/dev/projects/mhp-new/node_modules/husky/node_modules/execa/index.js
 - /mnt/d/work/dev/projects/mhp-new/node_modules/husky/lib/runner/index.js
 - /mnt/d/work/dev/projects/mhp-new/node_modules/husky/lib/runner/bin.js
 - /mnt/d/work/dev/projects/mhp-new/node_modules/husky/run.js

      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
      at Function.Module._load (internal/modules/cjs/loader.js:677:27)
      at Module.require (internal/modules/cjs/loader.js:830:19)
      at require (internal/modules/cjs/helpers.js:68:18)
      at Object.<anonymous> (/mnt/d/work/dev/projects/mhp-new/node_modules/husky/node_modules/cross-spawn/lib/parse.js:4:17)
      at Module._compile (internal/modules/cjs/loader.js:936:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
      at Module.load (internal/modules/cjs/loader.js:790:32)
      at Function.Module._load (internal/modules/cjs/loader.js:703:12)
      at Module.require (internal/modules/cjs/loader.js:830:19) {
        code: 'MODULE_NOT_FOUND',
        requireStack: [
            '/mnt/d/work/dev/projects/mhp-new/node_modules/husky/node_modules/cross-spawn/lib/parse.js',
            '/mnt/d/work/dev/projects/mhp-new/node_modules/husky/node_modules/cross-spawn/index.js', 
            '/mnt/d/work/dev/projects/mhp-new/node_modules/husky/node_modules/execa/index.js',       
            '/mnt/d/work/dev/projects/mhp-new/node_modules/husky/lib/runner/index.js',
            '/mnt/d/work/dev/projects/mhp-new/node_modules/husky/lib/runner/bin.js',
            '/mnt/d/work/dev/projects/mhp-new/node_modules/husky/run.js'
        ]
```

This tells me that husky somehow is hooking into post-receive or post-merge, which is fine, but I am confused as to which hooks are _actually_ supported - it appears that more hooks are supported than shown in git docs.

For example, inside .git/hooks, we have many more than are documented in the git docs:
```
applypatch-msg # has .sample hook from git
commit-msg # has .sample hook from git
# query-watchman # only affects git internal file watching
post-applypatch
post-checkout
post-commit
post-merge
post-receive
post-rewrite
post-update # has .sample hook from git
pre-applypatch # has .sample hook from git
pre-auto-gc
pre-commit # has .sample hook from git
pre-push # has .sample hook from git
pre-rebase # has .sample hook from git
pre-receive # has .sample hook from git
prepare-commit-msg # has .sample hook from git
push-to-checkout
sendemail-validate
update # has .sample hook from git
```

I set HUSKY_DEBUG=true in our CRA's .env file, so we can see what is going on in the future... but I just wanted to put this out there since I couldn't find anything via google or searching this project directly.

**Comment by typicode** [comment]
Hi @devinrhode2,

All Git hooks are supported. You can find details here https://github.com/typicode/husky#supported-hooks

Regarding the error, it seems like all modules weren't installed.

**Comment by devinrhode2** [comment]
I've since realized git pull triggers post-merge hook.
