### ISSUE TITLE
v4 (^4.0.0-beta.5): hooks not executing

### ISSUE THREAD

**Issue by xCykrix** [typicode/husky#607]
Always something going wrong for me haha, I cannot get hooks to execute in any project now for some reason. I am unsure what may have changed in my environment to cause such issues but it is driving me insane.

If I execute this from `Git Bash for Windows`, it acts as it should but it does not act correctly when using cygwin and I cannot seem to find the cause of it.

OS: `Windows 7`
Terminal: `GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)`
Git: `git version 2.21.0`
```sh
xCykrix@samuel-laptop ~/projects/test
$ HUSKY_DEBUG=1 npm install --save-dev husky@next

> husky@4.0.0-beta.5 preuninstall C:\cygwin\home\xCykrix\projects\test\node_modules\husky
> node husky uninstall

husky > Uninstalling git hooks
husky:debug Current working directory is C:\cygwin\home\xCykrix\projects\test\node_modules\husky
husky:debug INIT_CWD is set to C:\cygwin\home\xCykrix\projects\test
husky:debug Git rev-parse command returned:
husky:debug   --git-common-dir: .git
husky:debug   --show-prefix:
husky > Done

> husky@4.0.0-beta.5 install C:\cygwin\home\xCykrix\projects\test\node_modules\husky
> node husky install

husky > Setting up git hooks
husky:debug Current working directory is C:\cygwin\home\xCykrix\projects\test\node_modules\husky
husky:debug INIT_CWD is set to C:\cygwin\home\xCykrix\projects\test
husky:debug Git rev-parse command returned:
husky:debug   --git-common-dir: .git
husky:debug   --show-prefix:
husky:debug Package manager: npm
husky:debug Installing hooks in C:\cygwin\home\xCykrix\projects\test\.git\hooks
husky > Done

> husky@4.0.0-beta.5 postinstall C:\cygwin\home\xCykrix\projects\test\node_modules\husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ husky@4.0.0-beta.5
updated 1 package and audited 37 packages in 3.562s

xCykrix@samuel-laptop ~/projects/test
$ git add .

xCykrix@samuel-laptop ~/projects/test
$ HUSKY_DEBUG=1 git commit -m "feat: test commit"
husky:debug husky v4.0.0-beta.5 (created at 11/14/2019, 4:22:40 PM)
husky:debug pre-commit hook started
husky:debug Current working directory is /home/xCykrix/projects/test
husky:debug pre-commit hook started
husky > pre-commit (node v13.0.1)
husky:debug npx --no-install husky-run exited with 0 exit code
On branch master
nothing to commit, working tree clean

xCykrix@samuel-laptop ~/projects/test
$ git add .

xCykrix@samuel-laptop ~/projects/test
$ HUSKY_DEBUG=1 git commit -m "feat: test commit"
husky:debug husky v4.0.0-beta.5 (created at 11/14/2019, 4:22:40 PM)
husky:debug pre-commit hook started
husky:debug Current working directory is /home/xCykrix/projects/test
husky:debug pre-commit hook started
husky > pre-commit (node v13.0.1)
husky:debug npx --no-install husky-run exited with 0 exit code
husky:debug husky v4.0.0-beta.5 (created at 11/14/2019, 4:22:40 PM)
husky:debug prepare-commit-msg hook started
husky:debug Current working directory is /home/xCykrix/projects/test
husky:debug prepare-commit-msg hook started
husky:debug npx --no-install husky-run exited with 0 exit code
husky:debug husky v4.0.0-beta.5 (created at 11/14/2019, 4:22:40 PM)
husky:debug commit-msg hook started
husky:debug Current working directory is /home/xCykrix/projects/test
husky:debug commit-msg hook started
husky:debug npx --no-install husky-run exited with 0 exit code
husky:debug husky v4.0.0-beta.5 (created at 11/14/2019, 4:22:40 PM)
husky:debug post-commit hook started
husky:debug Current working directory is /home/xCykrix/projects/test
husky:debug post-commit hook started
husky:debug npx --no-install husky-run exited with 0 exit code
[master 5cd66f3] feat: test commit
 1 file changed, 1 insertion(+), 1 deletion(-)```

**Comment by xCykrix** [comment]
`.huskyrc.json`
```json
{
  "hooks": {
    "commit-msg": "exit 1",
    "pre-commit": "exit 1",
    "pre-push": "exit 1"
  }
}
```
`package.json` (snippit)
```json
  "devDependencies": {
    "husky": "^4.0.0-beta.5"
  },
  "husky": {
    "hooks": {
      "pre-commit": "exit 1"
    }
  }
```

----

### Below is using Git Bash (Acts as Expected)
```sh
xCykrix@samuel-laptop MINGW64 /c/cygwin/home/xCykrix/projects/test (master)
$ HUSKY_DEBUG=1 npm install --save-dev husky@next

> husky@4.0.0-beta.5 preuninstall C:\cygwin\home\xCykrix\projects\test\node_modules\husky
> node husky uninstall

husky > Uninstalling git hooks
husky:debug Current working directory is C:\cygwin\home\xCykrix\projects\test\node_modules\husky
husky:debug INIT_CWD is set to C:\cygwin\home\xCykrix\projects\test
husky:debug Git rev-parse command returned:
husky:debug   --git-common-dir: .git
husky:debug   --show-prefix:
husky > Done

> husky@4.0.0-beta.5 install C:\cygwin\home\xCykrix\projects\test\node_modules\husky
> node husky install

husky > Setting up git hooks
husky:debug Current working directory is C:\cygwin\home\xCykrix\projects\test\node_modules\husky
husky:debug INIT_CWD is set to C:\cygwin\home\xCykrix\projects\test
husky:debug Git rev-parse command returned:
husky:debug   --git-common-dir: .git
husky:debug   --show-prefix:
husky:debug Package manager: npm
husky:debug Installing hooks in C:\cygwin\home\xCykrix\projects\test\.git\hooks
husky > Done

> husky@4.0.0-beta.5 postinstall C:\cygwin\home\xCykrix\projects\test\node_modules\husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ husky@4.0.0-beta.5
updated 1 package and audited 37 packages in 3.454s

xCykrix@samuel-laptop MINGW64 /c/cygwin/home/xCykrix/projects/test (master)
$ git add .
warning: LF will be replaced by CRLF in .gitignore.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in package-lock.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in package.json.
The file will have its original line endings in your working directory

xCykrix@samuel-laptop MINGW64 /c/cygwin/home/xCykrix/projects/test (master)
$ git checkout
M       .gitignore
M       index.js
M       package-lock.json
M       package.json

xCykrix@samuel-laptop MINGW64 /c/cygwin/home/xCykrix/projects/test (master)
$ HUSKY_DEBUG=1 git commit -m "feat: test"
husky:debug husky v4.0.0-beta.5 (created at 11/14/2019, 4:28:23 PM)
husky:debug pre-commit hook started
husky:debug Current working directory is /c/cygwin/home/xCykrix/projects/test
husky:debug pre-commit hook started
husky > pre-commit (node v13.0.1)
husky:debug npx --no-install husky-run exited with 1 exit code
```

**Comment by Yegorich555** [comment]
I have similar behavior for versions (and it skips pre-commit hook):
Windows 10
husky: 4.2.3
node: 12.16.0
npm: 6.13.4

package.json
```
  "husky": {
    "pre-commit": "exit 1"
  }
```

package.json (the second version)
```
  "scripts": {
    "test": "node test.js" //file that has only:  throw new Error("test failed")
  },
  "husky": {
    "pre-commit": "npm test"
  }
```


console.log
``` 
> git commit --quiet --allow-empty-message --file -
husky:debug husky v4.2.3 - pre-commit
husky:debug Current working directory is /d/Projects/ChaseSoaClu360/Project_SPA
husky:debug npx --no-install husky-run exited with 0 exit code
husky:debug husky v4.2.3 - prepare-commit-msg
husky:debug Current working directory is /d/Projects/ChaseSoaClu360/Project_SPA
husky:debug prepare-commit-msg config not found, skipping hook //
husky:debug husky v4.2.3 - commit-msg
husky:debug Current working directory is /d/Projects/ChaseSoaClu360/Project_SPA
husky:debug commit-msg config not found, skipping hook
husky:debug husky v4.2.3 - post-commit
husky:debug Current working directory is /d/Projects/ChaseSoaClu360/Project_SPA
husky:debug post-commit config not found, skipping hook
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse develop
> git rev-parse --symbolic-full-name develop@{u}
> git rev-list --left-right develop...refs/remotes/origin/develop
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Failed to watch ref 'd:\Projects\ChaseSoaClu360\Project_SPA\.git\refs\remotes\origin\develop', is most likely packed.
Error: ENOENT: no such file or directory, watch 'd:\Projects\ChaseSoaClu360\Project_SPA\.git\refs\remotes\origin\develop'
	at FSWatcher.start (internal/fs/watchers.js:165:26)
	at Object.watch (fs.js:1270:11)
	at Object.t.watch (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:592056)
	at E.updateTransientWatchers (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:123260)
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:561)
	at R.updateModelState (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:142118)
> git config --get commit.template
> git ls-files --stage -- D:\Projects\ChaseSoaClu360\Project_SPA\package.json
> git cat-file -s 3b0874659fd52f558be81e0039c6c812e4f5e639
> git show :package.json
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse develop
> git rev-parse --symbolic-full-name develop@{u}
> git rev-list --left-right develop...refs/remotes/origin/develop
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Failed to watch ref 'd:\Projects\ChaseSoaClu360\Project_SPA\.git\refs\remotes\origin\develop', is most likely packed.
Error: ENOENT: no such file or directory, watch 'd:\Projects\ChaseSoaClu360\Project_SPA\.git\refs\remotes\origin\develop'
	at FSWatcher.start (internal/fs/watchers.js:165:26)
	at Object.watch (fs.js:1270:11)
	at Object.t.watch (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:592056)
	at E.updateTransientWatchers (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:123260)
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:561)
	at R.updateModelState (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\dist\main.js:1:142118)
> git config --get commit.template
```

For me, husky stopped to work with updating NodeJs from version 10.* to 12.*
Completely reinstalling NodeJs, creating new repository doesn't fix this

**Comment by xCykrix** [comment]
@Yegorich555 do you have anything unique about your environment? I have recently scraped that entire environment and reinstalled / manually reconfigured my environment path.

I was running Cygwin with plugins pertaining to build C/C++ and other misc things, and something about that setup was completely bad for the Git hooks.

I believe it was caused by the virtual mounting of my drive for Cygwin, as it was accessed via `/cygdrive/c/.../`, and Husky just couldn't handle that as it wasn't given much information to do so.

**Comment by Yegorich555** [comment]
Confirm. The mentioned directory exists. About special env: there is nothing that I did special and manually. I've just noticed that hooks completely stop working after updating NodeJs (but maybe this is not tied). I've worried about the following string in debug:
```
husky:debug npx --no-install husky-run exited with 0 exit code
```
looks like **npx** missed my code or even didn't handle exitCode. I'm not sure what is going wrong. Anyway, it's something that tied with the environment but I don't see any ways to resolve this. Can we improve debug for husky at least via direct changing code in my node_modules folder?

**Comment by xCykrix** [comment]
Sorry for the delayed response, I never got an email on this one haha.

Anyways, what console/bash emulator are you using? The WSL Ubuntu for Windows 10? Git Bash? Another?

**Comment by Yegorich555** [comment]
I use **PowerShellCore** for Windows 10

**Comment by KarolaPlichta** [comment]
I have the same problem as @Yegorich555 with the same versions. I use PowerShell and Git bash console. It starts work when I rollback husky to 3.1.0 version and then upgrade it version by version to 4.2.3.

**Comment by xCykrix** [comment]
I'm not too sure about your other two issues. It seems to be PowerShell specific between you two. Mine was an edge case environment where pathing to the file system was not resolvable as far as I know.

@Yegorich555 @KarolaPlichta If you two both make a blank folder on your Desktop, run `git init` and just a basic package.json with husky installed, does the issue persist?

Yegorich555 - If it does not persist for you, try doing the same thing on your D drive.

/cc @typicode

**Comment by Yegorich555** [comment]
As I mentioned earlier new-empty repository doesn't fix this issue. Moreover, I checked git commit in the different tools: GitKraken, Bash, PowerShell, VSCodeExtension - behavior the same: hooks are not executed

**Comment by wjessop** [comment]
I have this error too with a pre-push hook:

```
$ export HUSKY_DEBUG=1
$ git push --set-upstream origin ma_barnch
husky:debug husky v4.2.3 - pre-push
husky:debug Current working directory is /Users/will/my/repo
husky > pre-push (node v10.15.3)
husky > pre-push hook failed (add --no-verify to bypass)
husky:debug npx --no-install husky-run exited with 1 exit code
error: failed to push some refs to 'git@github.com:snippy/snip.git'
```

I seem to be able to run the install command that is mentioned:

```
$ npx --no-install husky-run
$ echo $?
0
```

I am using Mac OS 10.15.3 (Catalina), and bash as my shell (from homebrew).

**Comment by typicode** [comment]
Closing as v5 is quite different and may not have this issue. Feel free to open another issue if needed :)
