### ISSUE TITLE
Not uninstalling/installing hooks

### ISSUE THREAD

**Issue by zachdixon** [typicode/husky#647]
I'm having an issue with getting the correct CWD I think. My issue started out with `git commit` saying Husky required Node 10 or newer. I'm using lando and node 11.4. What's weird is I had it working fine yesterday, then after reinstalling my node packages, I started running into this error. Checking husky releases, it looks like there were 2 new ones between then and now, so I tried installing 4.0.7 with no luck, and started getting this for both versions:

```
lando npm i -D husky

> husky@4.0.9 preuninstall /app/wp-content/themes/t1/node_modules/husky
> node husky uninstall

husky > Uninstalling git hooks
husky:debug Current working directory is /app/wp-content/themes/t1/node_modules/husky
husky:debug INIT_CWD is set to /app/wp-content/themes/t1
husky:debug Git rev-parse command returned:
husky:debug   --git-common-dir: wp-content/themes/t1/.git
husky:debug   --show-prefix: wp-content/themes/t1/
husky > Done

> husky@4.0.9 install /app/wp-content/themes/t1/node_modules/husky
> node husky install

husky > Setting up git hooks
husky:debug Current working directory is /app/wp-content/themes/t1/node_modules/husky
husky:debug INIT_CWD is set to /app/wp-content/themes/t1
husky:debug Git rev-parse command returned:
husky:debug   --git-common-dir: wp-content/themes/t1/.git
husky:debug   --show-prefix: wp-content/themes/t1/
husky:debug Package manager: npm
ENOENT: no such file or directory, mkdir '/app/wp-content/themes/t1/wp-content/themes/t1/.git/hooks'
husky:debug Error: ENOENT: no such file or directory, mkdir '/app/wp-content/themes/t1/wp-content/themes/t1/.git/hooks'
    at Object.mkdirSync (fs.js:775:3)
    at Object.install (/app/wp-content/themes/t1/node_modules/husky/lib/installer/index.js:110:22)
    at run (/app/wp-content/themes/t1/node_modules/husky/lib/installer/bin.js:66:16)
    at Object.<anonymous> (/app/wp-content/themes/t1/node_modules/husky/lib/installer/bin.js:85:1)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
husky > Failed to install
```

Problem is, my git directory should be `/app`, but my package.json needs to be located at `/app/wp-content/themes/t1`.

The only thing I can think of is git version on the lando/docker container is 2.11 which obviously is < 2.13, but it was working fine yesterday, with the same git version. Could that be it though? I came here because I'm not sure if I can upgrade the git version, so just wanted to see if there may be another cause.

**Comment by zachdixon** [comment]
With a bit more digging, found out it definitely is the git version installed on the docker container which unfortunately only supports 2.11. So now I'm looking at workarounds to use husky with docker.
