### ISSUE TITLE
`TypeError: Cannot read property 'length' of null` when commiting without the `-m` flag and with an empty message

### ISSUE THREAD

**Issue by nunocastromartins** [typicode/husky#681]
### Error:
```
husky > pre-commit (node v13.9.0)
  ✔ Preparing...
  ✔ Running tasks...
  ✔ Applying modifications...
  ✔ Cleaning up...
husky > commit-msg (node v13.9.0)
[...]/node_modules/@commitlint/cli/lib/cli.js:124
        throw err;
        ^

TypeError: Cannot read property 'length' of null
    at exports.default ([...]/node_modules/@commitlint/rules/lib/header-max-length.js:10:143)
    at [...]/node_modules/@commitlint/lint/lib/index.js:151:17
    at Array.map (<anonymous>)
    at Object.<anonymous> ([...]/node_modules/@commitlint/lint/lib/index.js:131:7)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
husky > commit-msg hook failed (add --no-verify to bypass)
```

### Steps to reproduce:
1. `git commit`
2. Exit editor without writing a message

The commit is expected to fail due to the empty commit message, but Husky shouldn't throw an error. The behaviour appears to be correct when running `git commit -m ""`.

---

**Node version:** `13.9.0`
**Git version:** `2.25.1`
**Husky version:** `4.2.3`

**Comment by nunocastromartins** [comment]
I'm so sorry, I just realised that I should have filed this against `@commitlint/cli`. I guess I must be tired. :')
