### ISSUE TITLE
When running `npm clean-install` with `--prefix` options husky will fail to install because it does not honour the --prefix option

### ISSUE THREAD

**Issue by ebdrup** [typicode/husky#703]
```
~/$ HUSKY_DEBUG=1 npm clean-install --silent --prefix ./husky-test
husky > Setting up git hooks
husky:debug Current working directory is /code/husky-test/node_modules/husky
husky:debug INIT_CWD is set to /code/
Can't find package.json in /code/ directory or parents
Please check that your project has a package.json or create one and reinstall husky.
husky:debug Error: Can't find package.json in /code/ directory or parents
Please check that your project has a package.json or create one and reinstall husky.
    at getUserPkgDir (/code/husky-test/node_modules/husky/lib/installer/bin.js:46:15)
    at run (/code/husky-test/node_modules/husky/lib/installer/bin.js:63:28)
    at Object.<anonymous> (/code/husky-test/node_modules/husky/lib/installer/bin.js:88:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/code/husky-test/node_modules/husky/husky.js:20:3)
husky > Failed to install
added 2005 packages in 31.393s
```

**Comment by michaelw85** [comment]
I can confirm this is still an issue.

**Comment by typicode** [comment]
Thanks for the report, didn't know about the `--prefix` option. For v4, I don't think it'll be supported.
That said, the way v5 works, there shouldn't be such issue.
