### ISSUE TITLE
Yarn install fails if .yarnrc has --node_modules set

### ISSUE THREAD

**Issue by rslonik** [typicode/husky#748]
Hello, I use .yarnrc to set a different name to the node_modules, I include nosync so iCloud wont sync this folder.

Husky install fails because of this flag.

```
~/temp/husky-test % yarn add husky
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error /Users/rs/temp/husky-test/node_modules.nosync/husky: Command failed.
Exit code: 1
Command: node husky install
Arguments:
Directory: /Users/rs/temp/husky-test/node_modules.nosync/husky
Output:
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'please-upgrade-node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/rs/temp/husky-test/node_modules.nosync/husky/husky.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

OS: macOs Catalina
Terminal: iTerm

To reproduce: `yarn init` then set .yarnrc content to `--modules-folder node_modules.nosync`, then `yarn add husky`. It fails with the above output.

A workaround is to make a link from the custom folder to node_modules with `ln -s`

**Comment by typicode** [comment]
Hello @rslonik,

Thanks for the report. Not sure how to fix that in husky v4 code. That said, Husky 5 works quite differently and there are chances that it doesn't have this issue.

**Comment by typicode** [comment]
Feel free to reopen if you encounter such problem with v5.
