### ISSUE TITLE
Can't commit files using conventional commit

### ISSUE THREAD

**Issue by apilacharya** [typicode/husky#771]
Whenever I try to commit in my windows machine I got the following error.

```
$ git commit -m"foo"
husky > commit-msg (node v12.18.2)
E:\myproject\commitlint.config.js:1
��m


SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at module.exports (E:\js mega course\infinity scroll\node_modules\@commitlint\load\node_modules\import-fresh\index.js:31:59)
    at loadJs (E:\js mega course\infinity scroll\node_modules\@commitlint\load\node_modules\cosmiconfig\dist\loaders.js:16:18)
    at Explorer.loadFileContent (E:\js mega course\infinity scroll\node_modules\@commitlint\load\node_modules\cosmiconfig\dist\Explorer.js:84:32)
    at Explorer.createCosmiconfigResult (E:\js mega course\infinity scroll\node_modules\@commitlint\load\node_modules\cosmiconfig\dist\Explorer.js:89:36)
husky > commit-msg hook failed (add --no-verify to bypass)
```

Machine : Windows 10

I've included this line of code in `commitlint.config.js`

```js
module.exports = {extends: ['@commitlint/config-conventional']};
```

**Comment by typicode** [comment]
Looks good to me, so not sure why it's not working.

That said it doesn't seem to be related to husky directly since `husky > commit-msg (node v12.18.2)` and `husky > commit-msg hook failed (add --no-verify to bypass)` are displayed. Meaning that husky did run successfully but the underlying command failed.
