### ISSUE TITLE
"Could not determine executable to run"

### ISSUE THREAD

**Issue by hyoretsu** [typicode/husky#933]
I set up WSL 2 on Windows with Oh-my-zsh and Node with NVM. However, I receive the error in title when creating a commit through Zsh or GitKraken (though the latter one's through Windows)

Already tried [bobrosoft's solution](https://github.com/typicode/husky/issues/77#issuecomment-630065185) in both .huskyrc and .zshrc (changing `~/.bash_profile` to `~/.zshrc`), plus [the one in FAQ](https://typicode.github.io/husky/#/?id=command-not-found). None worked, though my NVM installation already created this in .zshrc
```
### Added by NVM Installer
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
### End of NVM Installer section
```
Which, as far as I could check, does the same thing as both solutions. Here's my log of the error:
```
0 verbose cli [
0 verbose cli   '/home/hyoretsu/.nvm/versions/node/v14.16.0/bin/node',
0 verbose cli   '/home/hyoretsu/.nvm/versions/node/v14.16.0/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'husky-run'
0 verbose cli ]
1 info using npm@7.8.0
2 info using node@v14.16.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/hyoretsu/.nvm/versions/node/v14.16.0/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/hyoretsu/@Projects/reactjs-template/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/home/hyoretsu/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/home/hyoretsu/.nvm/versions/node/v14.16.0/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 8ms
18 timing npm:load:configload Completed in 8ms
19 timing npm:load:setTitle Completed in 0ms
20 timing npm:load:setupLog Completed in 1ms
21 timing npm:load:cleanupLog Completed in 2ms
22 timing npm:load:configScope Completed in 0ms
23 timing npm:load:projectScope Completed in 0ms
24 timing npm:load Completed in 12ms
25 timing config:load:flatten Completed in 2ms
26 timing command:exec Completed in 371ms
27 verbose stack Error: could not determine executable to run
27 verbose stack     at Exec.getBinFromManifest (/home/hyoretsu/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/exec.js:330:25)
27 verbose stack     at Exec._exec (/home/hyoretsu/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/exec.js:168:22)
28 verbose cwd /home/hyoretsu/@Projects/reactjs-template
29 verbose Linux 5.4.72-microsoft-standard-WSL2
30 verbose argv "/home/hyoretsu/.nvm/versions/node/v14.16.0/bin/node" "/home/hyoretsu/.nvm/versions/node/v14.16.0/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "husky-run"
31 verbose node v14.16.0
32 verbose npm  v7.8.0
33 error could not determine executable to run
34 verbose exit 1
```

**Comment by typicode** [comment]
`husky-run` seems to be related to husky 4. Could you try updating to 6?
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v6

**Comment by hyoretsu** [comment]
Oh ok, so we changed major versions and it uses SH files now. That fixed it.
