### ISSUE TITLE
ENOTDIR: not a directory, mkdir '.husky/_'

### ISSUE THREAD

**Issue by dschinkel** [typicode/husky#955]
**what is going on here?**

`npm set-script prepare "husky install" && npm run prepare`

```
> we-do-tdd@0.0.2 prepare
> husky install

husky - Git hooks failed to install
/Users/daveschinkel/code/projects/we-do-tdd/node_modules/husky/lib/index.js:33
        throw e;
        ^

Error: ENOTDIR: not a directory, mkdir '.husky/_'
    at Object.mkdirSync (fs.js:947:3)
    at Object.install (/Users/daveschinkel/code/projects/we-do-tdd/node_modules/husky/lib/index.js:23:12)
    at Object.install (/Users/daveschinkel/code/projects/we-do-tdd/node_modules/husky/lib/bin.js:27:41)
    at Object.<anonymous> (/Users/daveschinkel/code/projects/we-do-tdd/node_modules/husky/lib/bin.js:39:22)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -20,
  syscall: 'mkdir',
  code: 'ENOTDIR',
  path: '.husky/_'
```

**Comment by dschinkel** [comment]
sigh, I had an existing .husky file which somehow caused this error.  Removed the file, it's fine now.
