### ISSUE TITLE
"_" folder already exists

### ISSUE THREAD

**Issue by JaydenGui** [typicode/husky#999]
after "yarn"
$ husky install
husky - Git hooks failed to install
D:\iWork\project\node_modules\husky\lib\index.js:33
        throw e;
        ^

Error: EEXIST: file already exists, mkdir 'D:\iWork\project\.husky\_'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.install (D:\iWork\project\node_modules\husky\lib\index.js:23:12)
    at Object.install (D:\iWork\project\node_modules\husky\lib\bin.js:27:41)
    at Object.<anonymous> (D:\iWork\project\node_modules\husky\lib\bin.js:39:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Context**
- package.json config script "prepare": "husky install"

`fs.mkdirSync(path.join(dir, '_'), { recursive: true });`  not check whether the folder has been existed?

**Comment by typicode** [comment]
What's your version of Node?
With Node v16, I'm not getting the issue:

```
$ node
Welcome to Node.js v16.2.0.
Type ".help" for more information.
> require('fs').mkdirSync('foo', { recursive: true })
'foo'
> require('fs').mkdirSync('foo', { recursive: true })
undefined
```

**Comment by JaydenGui** [comment]
D:\iWork\project>nvm list

    12.20.0
  * 8.17.0 (Currently using 64-bit executable)
  
I tried again. 8.17.0 failed and 12.20.0 is OK

**Comment by typicode** [comment]
Thanks for the update. I guess it can be closed then :)

**Comment by liuliangsir** [comment]
It also shows error above when using 8.11.3
